#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
enabled=`uci get linkease.config.enabled 2>/dev/null`
if [ "$enabled" == 1 ]; then
	killall -q link-ease 2>/dev/null
	logger=`uci get linkease.config.logger 2>/dev/null`
	[ "$logger" == 1 ] && logto="> /tmp/linkease.log 2>&1"
	procd_open_instance
	procd_set_param command link-ease $logto
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
fi
}

service_triggers() {
	procd_add_reload_trigger "linkease"
}

stop_service() {
	killall -q link-ease 2>/dev/null
}

restart() {
	stop
	start
}


